import { DashboardImages } from './shape';

const appImages: DashboardImages = {
    buttonArrowPrimary: require('assets/img/dashboard/primary-arrow.svg'),
    backArrow: require('assets/img/dashboard/back-arrow.svg'),
    logo: require('assets/img/dashboard/app-coach-logo.svg'),
    signInVisual: require('assets/img/dashboard/sign-in-visual.svg'),
    editIcon: require('assets/img/dashboard/edit-icon.svg'),
    questionIcon: require('assets/img/dashboard/question-icon.svg'),
    transcriptionIcon: require('assets/img/dashboard/view-transcription-icon.svg'),
    toDesktopVisual: require('assets/img/dashboard/desktop-visual.svg'),
    iconAddLink: require('assets/img/dashboard/add-link.svg'),
    iconUploadFile: require('assets/img/dashboard/upload-icon.svg'),
    iconPrompt: require('assets/img/dashboard/icon-prompt.svg'),
    infographicCardArrowUpIcon: require('assets/img/dashboard/infograph-icon-up.svg'),
    infographicCardArrowDownIcon: require('assets/img/dashboard/infograph-icon-down.svg'),
    infographicCardNoneIcon: require('assets/img/dashboard/infograph-icon-none.svg'),
    clientIcon: require('assets/img/dashboard/client-icon.svg'),
    iconInterventions: require('assets/img/dashboard/icon-interventions.svg'),
    depressedIcon: require('assets/img/dashboard/depressed.svg'),
    sadIcon: require('assets/img/dashboard/sad.svg'),
    neutralIcon: require('assets/img/dashboard/neutral.svg'),
    happyIcon: require('assets/img/dashboard/happy.svg'),
    excitedIcon: require('assets/img/dashboard/excited.svg'),
    JournaPlaceholder: require('assets/img/dashboard/journal-placeholder.svg'),
    SuccessSendVisual: require('assets/img/dashboard/link-sent-visual.svg'),
    noClientsVisual: require('assets/img/dashboard/no-clients-visual.svg'),
    SignUpCompleteVisual: require('assets/img/dashboard/signup-complete.svg'),
    TimeTrackingEmptyVisual: require('assets/img/dashboard/timetracking-empty.svg'),
    waitingVisual: require('assets/img/dashboard/waiting-approval.svg'),
    clientsHeaderIcon: require('assets/img/dashboard/clients.svg'),
    addClientHeaderIcon: require('assets/img/dashboard/plus-icon.svg'),
    helpHeaderIcon: require('assets/img/dashboard/help-icon.svg'),
    DocsPlaceholder: require('assets/img/dashboard/docs-placeholder.svg'),
    AvatarPlaceholderClient: require('assets/img/default-avatar.svg'),
    clockSessionInner: require('assets/img/dashboard/clock.svg'),
    pinSessionInner: require('assets/img/dashboard/pin.svg'),
    bubblePlaceholder: require('assets/img/dashboard/bubbles-placeholder2.svg'),
    emptyDataGradientChart: require('assets/img/dashboard/empty-data-icon.svg'),
    docIconDoc: require('assets/img/dashboard/doc-icon-doc.svg'),
    docIconImage: require('assets/img/dashboard/doc-icon-image.svg'),
    docIconLink: require('assets/img/dashboard/doc-icon-link.svg'),
    docIconMedia: require('assets/img/dashboard/doc-icon-media.svg'),
    docIconOther: require('assets/img/dashboard/doc-icon-other.svg'),
    GoalsPlaceholder: require('assets/img/dashboard/goals-placeholder.svg'),
    lockJournalInner: require('assets/img/lock-journalInner.svg'),
    checkedIcon: require('assets/img/checked-icon.svg'),
    infoMessageIcon: require('assets/img/dashboard/info-message-icon.svg'),
    copyIcon: require('assets/img/dashboard/copy-icon.svg'),
    printIcon: require('assets/img/dashboard/print-icon.svg'),
};

export default appImages;
