export const QUESTIONS_COUNT = 8;

export const GeneralPrompts = [
    "What's on your mind?",
    'How are you doing?',
    'How are you feeling?',
    'Talk to me.',
    "What's up?",
    "How's it going?",
    'Jump right in.',
    "How's today?",
    "What's happening?",
    "Tell me what's on your mind.",
    'What do you have to share today?',
    'What did you do today?',
    'How are you?',
    'What are you thinking?',
    "What's new?",
    "What's new today?",
    "How's the day going?",
    'How are you doing right now?',
    "What's on your mind right now?",
    "What's good?",
    'What made you laugh today?',
];

export const MainPrompts = [
    'What made you proud today?',
    'What did you dream about last night?',
    'What made you smile today?',
    'What did you do for someone you care about today?',
    'Did you feel empathetic today?',
    'Did you feel hopeful today?',
    'What makes you happy?',
    'What do you most want right now?',
    'Whose lives did you affect today?',
    'Give yourself a pep talk.',
    'Who are you grateful for today?',
    'What are you grateful for today?',
    "Share three things you're grateful for.",
    'What advice would you give yourself?',
    'What makes you feel alive?',
    "What's a challenge you're facing currently?",
    'What would a friend say to reassure you?',
    'How could you give yourself some credit?',
    'When are you courageous?',
    'What are 3 things you want to congratulate yourself on?',
    'What are 3 positive traits other people see in you?',
    'What are 3 compliments you receive on a regular basis?',
    "Tell me 3 things you're good at.",
    'What are 3 things that make you laugh?',
    'Share 3 things that excite you about the future.',
    "What's your perfect pizza?",
    'What shape is your life?',
    "What are the three possessions you can't live without?",
    'What are your Sunday rituals?',
    'In which ways does the full moon affect your behavior?',
    'What are your favorite smells?',
    'Have you had any telepathic or paranormal experiences?',
    'What beauty tricks do you perform to make yourself look "better"?',
    "What's the last compliment you gave?",
    "What are 3 extravagant things you'd buy if you had unlimited funds?",
    'What color do you feel like right now?',
    "What's your pet peeve?",
    "What goes through your head when you're on telephone hold?",
    'Which pieces of modern technology have most shaped you?',
    'What food is always left in your refrigerator after everything else is gone?',
    "Tell me about an epic prank you've pulled off.",
    'Sing to me.',
    'Which superhero(ine) do you relate to?',
    'What are three ideas you disagree with?',
    'Do any animals scare you?',
    'Tell me about your typical daydreams.',
    "What are the best gifts you've been given?",
    'I always sleep facing...',
    "Tell me the names you've been called, endearing and not so.",
    'What goes through your mind before you go to sleep?',
    'What do you wish when you blew out your birthday candles?',
    "What's under your kitchen sink?",
    'What do you do between turning off the alarm and walking out the front door?',
    "List all the modes of transportation you've ever taken",
    'What are 10 regular daily items you wish you never had to buy again',
    "What are all the greetings you've ever used to answer your telephone?",
    'What is something you could leave behind?',
    'What motivates you?',
    "How do you know if you've been successful?",
    'What do you find beautiful?',
    'Who do you admire?',
    'What scares you?',
    "Share a memory you don't want to forget.",
    'What would you do today if you had more time?',
    'Tell me one of your favorite memories.',
    'What do you want to learn?',
    'What did you enjoy when you were a kid?',
    'Tell me about the things that slow you down.',
    "What thought patterns aren't helping you?",
    "What is a dream that hasn't come true yet?",
    "What's worrying you? Get it off your chest.",
    'Do you feel stressed today? Talk it off.',
    'What are your top 3 sources of strength?',
    'How can the people around you help?',
    "Think of a challenge you're facing. What's the first step?",
    "What's one thing you can do to make yourself happy right now?",
    "What's a nice thing someone did for you today?",
    'What 3 things are you grateful for today?',
    'Who would you be unable to live without?',
    'What sounds can you hear right now?',
    'What smell do you love smelling the most?',
    'Which emotion is your favorite to experience?',
    'What have you learned from unpleasant emotions?',
    'What is your favorite physical trait?',
    'Who was the last person you hugged?',
    'What opportunities have changed your life?',
    'What character traits are you happy to have?',
    'What luxury are you lucky to have access to?',
    "What inspires you to keep going when it's hard?",
    'How does it feel to eat a really great meal?',
    'When did you last feel really cozy?',
    'When did you last look up at the stars?',
    'How does it feel to give a gift?',
    'When were you last encouraged?',
    'How do you feel in moments spent alone?',
    "How does a good night's sleep feel?",
    'Do you tend to remember your dreams?',
    'Do you life dream or sleep dream?',
    'Describe a recurring dream you have.',
    'If you could change one thing about your dreams, what would it be?',
    'The purpose of dreaming is...',
    'The purpose of night dreaming is...',
    'The purpose of day dreaming is...',
    "What's a nice thing you did for someone today?",
    "What's one kind thing you could do for yourself right now?",
    'How could you show kindness to someone today?',
    'Who could you show kindness to today?',
    "What's a small way you can help someone today?",
    "Who's in need around you?",
    "What's a cause you care about?",
    'How do you think people feel when you do something kind for them?',
    "What would life be like if someone didn't help you out today?",
    'How does it make you feel to give a compliment?',
    'How does it make you feel to get a compliment?',
    'What will you regret not having done?',
    'What would your 90 year old self wish you did today?',
    'Are you into aliens?',
    'Do you follow any diets?',
    'What are your top 3 movies?',
    'Do you play any sports?',
    'What are your top 3 books?',
    'How many cookies have you eaten in one sitting?',
    'Where have you traveled?',
    'Do you believe in life after love?',
    'Can you dance?',
    'Vanilla or chocolate?',
    'Why is the sky blue?',
    "What's your favorite color?",
    'Are you a morning person or a night owl?',
    'Do you have a best friend?',
    "What's the last thing you've created?",
    "What's your favorite dinosaur?",
    "What's your favorite sea creature?",
    'Can you swim?',
    'Where do you want to travel?',
    'What are the last 3 things you felt proud of?',
    'Who do you look up to?',
    'Has someone done it before?',
    'Who could mentor you?',
    'Do you want to be an expert at something?',
    'Are you an expert at something?',
    'Who can inspire you daily?',
    "What's the best case scenario?",
    'Who is helping you?',
    'Put me down and go on a micro adventure.',
    'What games did you play as a kid?',
    'What does joy feel like in your body?',
    'What color is joy?',
    "Who's the happiest person you know?",
    "Who's the most joyful person you know?",
    "What habit isn't serving your happiness?",
    'Show some kindness to yourself right now.',
    'What do you do to take care of yourself?',
    'Who inspires you to be more kind?',
    'What prevents you from being kind?',
    'What triggers you to be unkind?',
    'Tell me about an object that brings a smile to your face.',
    'Tell me about a time you listened to your gut.',
    'Tell me about a time you ilstened to your intuition.',
    'Where do you feel mistrust in your body?',
    'Describe what intuition means to you today.',
    'Intuitively tell me something.',
    'Start talking without thinking.',
    'Let yourself do something new today.',
    'Listen...what do YOU want to do right now?',
    'Who censors you?',
    'What censors you?',
    'What is art?',
    'Do you consider yourself an "artist"?',
    'What would you need to do to consider yourself an artist?',
    'What makes you you?',
    'How would your best friend describe you?',
    'Describe your morning today.',
    "What's your happy place?",
    "What's your favorite time of day?",
    "When's the last time you spent time outside?",
    'Ready set go!',
    'Find something beautiful and tell me about it.',
    'Do something beautiful for someone today.',
];

export function getRandomQuestionsGroup() {
    const result = [];

    const source = getBase(result);

    while (result.length < QUESTIONS_COUNT) {
        const i = addRandomString(source, result);
        source.splice(i, 1);
    }

    return result;
}

function getBase(target: string[]) {
    addRandomString(GeneralPrompts, target);

    return MainPrompts.slice();
}

function addRandomString(source: string[], target: string[]): number {
    const i = getRandomIndex(source.length);
    target.push(source[i]);
    return i;
}

function getRandomIndex(arrLength: number): number {
    return Math.floor(Math.random() * arrLength);
}
