require File.join(File.dirname(`node --print "require.resolve('expo/package.json')"`), "scripts/autolinking")
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '13.0'

target 'CompanionKit' do
  use_expo_modules!
  config = use_native_modules!

  use_react_native!(:path => config[:reactNativePath])

  pod 'ExpoModulesCore', :path => "../node_modules/expo-modules-core/ios"



  target 'CompanionKitTests' do
    inherit! :complete
    # Pods for testing
  end

  use_flipper!()

  post_install do |installer|
	    react_native_post_install(installer)
	    # __apply_Xcode_12_5_M1_post_install_workaround(installer)
  end
    
  end

target 'CompanionKit-tvOS' do
  # Pods for CompanionKit-tvOS

  target 'CompanionKit-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end

pod 'GoogleSignIn'
