
export const Strings = {
    Ok: 'OK',
    Cancel: 'Cancel',
    Submit: 'Submit',
    TryAgain: 'Try Again',
    Logout: 'Logout',
    ThinkItsAMistake: 'Think there’s a mistake?',
    ContactUs: 'Contact Us',
    ForgotPassword: 'Forgot password?',
    Validation: {
        Empty: 'This field is required',
        Name: 'Invalid name format',
        Email: 'Please enter a valid email address',
        Password: 'Invalid password format: should be at least 6 characters and include English letters or numbers.',
        EnglishOnly: 'Only English letters supported',
        URL: 'Invalid URL format',
        Phone: 'Invalid phone number format',
        PhoneCountry: 'Invalid phone number: only US numbers are supported',
        CreditCard: 'Invalid credit card number format',
        CreditCardExpiryDate: 'Invalid expiry date format',
        CreditCardCvv: 'Invalid CVV format',
        PasswordsShouldMatch: 'Passwords should match',
        FirstName: 'First name is required',
        LastName: 'Last name is required',
        Occupation: 'What\'s your client\'s job?',
        Relationship: 'What\'s is caretaker\'s relationship with your client?',
        Birthday: 'Wrong birthday date',
        Goal: 'Choose a goal to achieve',
        FutureDate: 'Date should be in the future',
        NotFutureDate: 'Date cannot be in the future',
        InvalidDate: 'Chosen date is invalid',
        TextLength: 'Text cannot be longer than {length} symbols',
        InvalidInteger: 'Value should be normal integer',
        MaxValue: 'Field value cannot be higher than {max}',
        Zipcode: 'Please enter a valid US zip code',
    },
    UnknownServerError: 'Something went wrong and we were not able to process your request. Please contact the administrator.',
    ClientStatuses: {
        Active: 'Active',
        Invited: 'Invited',
        Inactive: 'Inactive',
    },
    BubbleChartStatus: {
        Things: 'Things',
        People: 'People',
        Places: 'Places',
    },
    Locations: {
        AtWork: 'At work',
        AtSchool: 'At school',
        OnAWalk: 'On a walk',
        InThePark: 'At the park',
        Somewhere: 'Elsewhere',
        AtHome: 'At home',
        InTransit: 'In transit',
    },
    Sentiments: {
        Undefined: 'Unknown',
        VeryPositive: 'Very Positive',
        Positive: 'Positive',
        Mixed: 'Mixed',
        Difficult: 'Difficult',
        Rough: 'Rough',
    },
    Periods: {
        ThisWeek: 'this week',
        Month: 'this month',
        Months3: 'last 3 months',
        Months6: 'last 6 months',
    },
    PromptCategories: {
        Any: 'Any',
        Anxiety: 'Anxiety',
        Anger: 'Anger',
        Depression: 'Depression',
        Neutral: 'Neutral',
    },
    FirebaseErrors: <{ [ errorCode: string ]: string }>{
        'auth/wrong-password': 'The password is invalid.',
    },
};

export type StringsShape = typeof Strings;
