name: build
on: push
jobs:
  all:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Create environment file
        run: cp test.env .env
      - name: Use correct node version
        uses: actions/setup-node@v2
        with:
          node-version: '10'
      - name: Initialize project
        run: ./bin/setup.bash -y -p 0 -f 1 -s 1
      - name: Show firebase dependencies (root)
        run: yarn list | grep firebase
      - name: Show firebase dependencies (server)
        working-directory: server/functions
        run: yarn list | grep firebase
      - name: Lint functions code
        run: yarn lint:server
      - name: Build server
        run: yarn build:server
      - name: Build dashboard
        run: yarn build:dashboard
