name: with-mock-backend
on: push
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v2
      - name: Create shared network
        run: docker network create bb_default
      - name: Create environment file
        run: cp test.env .docker.env
      - name: Start mock api service
        run: docker-compose up -d api
      - name: Build project
        run: docker-compose build server
      - name: Perform Tests
        run: docker-compose run --rm server yarn test
